// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var list;
    return list = new List('tables-list', {
      valueNames: ['sqlboss-table'],
      page: 3000
    });
  });

}).call(this);
