// Generated by CoffeeScript 1.3.3
(function() {
  var activate_connection, activate_connection_using_hash, search;

  search = function(keyword, connection_id) {
    return $('.database').each(function() {
      var database;
      database = $(this);
      if (database.data('database_name').toLowerCase().indexOf(keyword) >= 0 && (connection_id === 'all' || parseInt(connection_id) === parseInt(database.data('connection_id')))) {
        return database.show();
      } else {
        return database.hide();
      }
    });
  };

  activate_connection = function(connection_id) {
    $('.connection').removeClass('active');
    $(".connection[data-connection_id=" + connection_id + "]").addClass('active');
    return search($('#databases-search').val(), connection_id);
  };

  activate_connection_using_hash = function() {
    var connection_id;
    if (window.location.hash) {
      connection_id = window.location.hash.slice(1);
      return activate_connection(connection_id);
    }
  };

  $(function() {
    window.onhashchange = activate_connection_using_hash;
    activate_connection_using_hash();
    $('.connection a').click(function() {
      var connection, connection_id;
      $('.connection').removeClass('active');
      connection = $(this);
      connection.parent('li').addClass('active');
      connection_id = connection.attr('href').slice(1);
      return search($('#databases-search').val(), connection_id);
    });
    return $('#databases-search').keyup(function() {
      var connection_id, keyword;
      keyword = this.value.toLowerCase();
      connection_id = $('.connection.active a').attr('href').slice(1);
      return search(keyword, connection_id);
    });
  });

}).call(this);
