// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return $('.connection a').click(function() {
      var connection, connection_id;
      $('.connection').removeClass('active');
      connection = $(this);
      connection.parent('li').addClass('active');
      connection_id = connection.attr('href').substring(1);
      if (connection_id === 'all') {
        return $('.database').show();
      } else {
        $('.database').hide();
        return $(".database[data-connection_id=" + connection_id + "]").show();
      }
    });
  });

}).call(this);
