<?php
$config = array(
    'GOOGLE_APP_NAME' => getenv('GOOGLE_APP_NAME'),
    'GOOGLE_OAUTH_CLIENT_ID' => getenv('GOOGLE_OAUTH_CLIENT_ID'),
    'GOOGLE_OAUTH_CLIENT_SECRET' => getenv('GOOGLE_OAUTH_CLIENT_SECRET'),
    'GOOGLE_OAUTH_REDIRECT_URI' => getenv('GOOGLE_OAUTH_REDIRECT_URI'),
    'GOOGLE_OAUTH_SCOPE' => getenv('GOOGLE_OAUTH_SCOPE'),
    'GOOGLE_OAUTH_ALLOWED_DOMAINS' => getenv('GOOGLE_OAUTH_ALLOWED_DOMAINS'),
);