// Generated by CoffeeScript 1.7.1
(function() {
  $((function(_this) {
    return function() {
      var cursor, public_checkbox, query_editor, query_field, query_form;
      public_checkbox = $('#query-public').prev();
      if (public_checkbox.prop('checked')) {
        $('#query-public').addClass('btn-primary active');
      }
      $('#query-public').click(function() {
        $(this).toggleClass('btn-primary active');
        return public_checkbox.prop('checked', !public_checkbox.prop('checked'));
      });
      query_editor = ace.edit('query_sql_editor');
      query_editor.setTheme('ace/theme/tomorrow');
      query_editor.setFontSize('14px');
      query_editor.setShowInvisibles(true);
      query_editor.setDisplayIndentGuides(true);
      query_editor.setHighlightActiveLine(false);
      query_editor.getSession().setUseWrapMode(true);
      query_editor.getSession().setUseSoftTabs(false);
      query_editor.getSession().setMode('ace/mode/pgsql');
      query_editor.getSession().setTabSize(2);
      if ((typeof localStorage !== "undefined" && localStorage !== null) && (cursor = JSON.parse(localStorage.getItem('cursor')))) {
        query_editor.moveCursorToPosition(cursor);
      }
      query_form = $('#QueryIndexForm');
      query_field = $('#QueryQuerySql');
      query_form.submit(function(e) {
        query_field.val(query_editor.getSession().getValue());
        localStorage.setItem('cursor', JSON.stringify(query_editor.getCursorPosition()));
        return true;
      });
      $(window).keydown(function(e) {
        if (e.keyCode === 116 || (e.keyCode === 13 && e.shiftKey)) {
          e.preventDefault();
          return query_form.submit();
        }
      });
      return $("table.table-float").floatThead();
    };
  })(this));

}).call(this);
